modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/ToCraft/craftedcore/issues"
displayURL = "https://github.com/ToCraft/craftedcore"
license = "LGPL-3.0"

[[mods]]
modId = "craftedcore"
version = "${version}"
displayName = "CraftedCore"
authors = "To_Craft"
description = '''
My libary mod to make mods more compatible with modloaders
'''
logoFile = "icon.png"

[[dependencies.craftedcore]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft},)"
ordering = "NONE"
side = "BOTH"
