org.gradle.jvmargs=-Xmx4G
# Base Versions
modid=craftedcore
mod_version=8.2
artifact_type=release
maven_group=dev.tocraft
# Loader Versions
fabric_loader=0.19.3
neoform_version=26.2-2
mixinextras_version=0.5.4
# Upload data
curseforge_id=923377
modrinth_id=Dg7PHdkJ
optional_dependencies=cloth-config
# Discord Webhook
ping_role=1247931121019261070
# <--- ModMaster --->
minecraft=26.2
supported_versions=26.2
java=25
fabric=0.157.0+26.2
neoforge=26.2.0.59
# Dependencies
modmenu_version=20.0.1
cloth_config_version=26.2.155