org.gradle.jvmargs=-Xmx4G
# Base Versions
modid=craftedcore
mod_version=8.3.0
artifact_type=release
maven_group=dev.tocraft
# Loader Versions
fabric_loader=0.19.5
neoform_version=26.3-1
mixinextras_version=0.5.5
# Upload data
curseforge_id=923377
modrinth_id=Dg7PHdkJ
optional_dependencies=cloth-config
# Discord Webhook
ping_role=1247931121019261070
# <--- ModMaster --->
minecraft=26.3
supported_versions=26.3
java=25
fabric=0.161.0+26.3
neoforge=26.3.0.7-beta
# Dependencies
modmenu_version=21.0.0-beta.1
cloth_config_version=26.3.158
