modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "LGPL-3.0"

[[mods]]
modId = "testmod"
version = "0.1"
displayName = "TestMod"
authors = "To_Craft"
description = '''
Mod to test CraftedCore
'''

[[dependencies.testmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"
